# Generated by Django 4.1.2 on 2024-01-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='materials',
            field=models.CharField(default=2001, max_length=250),
            preserve_default=False,
        ),
    ]
