# Generated by Django 4.1.2 on 2024-01-24 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_userdetails_materials_provide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='account_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bankapp.accounttype'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bankapp.branches'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bankapp.district'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='materials',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
